"""Regression coverage for schema references used by example generation."""
from __future__ import annotations

from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / ".agentic/tests"))

from source_only import skip_unless_source_repo  # noqa: E402


def file_bytes(root: Path):
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in root.rglob("*")
        if path.is_file()
    }


class GenerateExamplesSchemaReferencesTests(unittest.TestCase):
    def test_AWF32_R1_011_controller_example_commands_are_complete_and_ordered(self):
        document = (ROOT / ".agentic/docs/34-CONTINUOUS-CONTROLLER.md").read_text(
            encoding="utf-8"
        )
        ordered = [
            "git -C $SOURCE_ROOT worktree add --detach $WORKTREE_ROOT $HEAD",
            "Copy-Item (Join-Path $WORKTREE_ROOT",
            "$adapter=Get-Content $ADAPTER_CONFIG",
            "$adapter.codex.executable.path=$CODEX_EXE",
            "$adapter.codex.worktree_root=$WORKTREE_ROOT",
            "$adapter.github.repository=[string]$repo.full_name",
            "$adapter.github.executable.sha256=",
            "$adapter.jira.cloud_id=$JIRA_CLOUD",
            "$adapter.jira.controller_actor_id=$CONTROLLER_ACTOR",
            "$adapter | ConvertTo-Json -Depth 100 | Set-Content $ADAPTER_CONFIG",
            "@{project_id=$PROJECT_ID;repository_id=[string]$repo.id;scope_sha256=$SCOPE_SHA256}",
            "$ticket=@{",
            "& $GH_EXE issue create",
            "function New-ObservationTime",
            "$COMMON=@(",
            "function Invoke-ControllerCycle",
            "if (Test-Path $STOP_FILE)",
            "& $PYTHON @COMMON cycle",
            "& $PYTHON @COMMON jira-lifecycle",
            "observed_at=$NOW;jira_binding=",
            "& $PYTHON @COMMON merge-observed",
            "Move-Item -LiteralPath $temporaryStop -Destination $STOP_FILE",
        ]
        positions = [document.find(marker) for marker in ordered]
        self.assertNotIn(-1, positions, dict(zip(ordered, positions)))
        self.assertEqual(sorted(positions), positions)

    @skip_unless_source_repo(
        "needs generate_examples.py and its checked-in generated outputs",
        "scripts/generate_examples.py",
    )
    def test_AWF16_CI_38043292294_schema_refs_preserve_generated_bytes(self):
        with tempfile.TemporaryDirectory(prefix="awf-generate-examples-") as raw:
            repository = Path(raw) / "source"
            shutil.copytree(
                ROOT,
                repository,
                ignore=shutil.ignore_patterns(
                    ".git", ".venv", ".tmp", ".tmp-tests", "__pycache__", "*.pyc"
                ),
            )
            before = file_bytes(repository)

            completed = subprocess.run(
                [sys.executable, "-B", "scripts/generate_examples.py"],
                cwd=repository,
                capture_output=True,
                text=True,
                timeout=300,
            )

            self.assertEqual(
                0,
                completed.returncode,
                f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}",
            )
            after = file_bytes(repository)
            changed = sorted(
                relative
                for relative in before.keys() | after.keys()
                if before.get(relative) != after.get(relative)
            )
            self.assertEqual([], changed, "generated bytes changed")


if __name__ == "__main__":
    unittest.main()
