"""Regression coverage for schema references used by example generation."""
from __future__ import annotations

from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / ".agentic/tests"))

from source_only import skip_unless_source_repo  # noqa: E402


def file_bytes(root: Path):
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in root.rglob("*")
        if path.is_file()
    }


class GenerateExamplesSchemaReferencesTests(unittest.TestCase):
    @skip_unless_source_repo(
        "needs generate_examples.py and its checked-in generated outputs",
        "scripts/generate_examples.py",
    )
    def test_AWF16_CI_38043292294_schema_refs_preserve_generated_bytes(self):
        with tempfile.TemporaryDirectory(prefix="awf-generate-examples-") as raw:
            repository = Path(raw) / "source"
            shutil.copytree(
                ROOT,
                repository,
                ignore=shutil.ignore_patterns(
                    ".git", ".venv", ".tmp", ".tmp-tests", "__pycache__", "*.pyc"
                ),
            )
            before = file_bytes(repository)

            completed = subprocess.run(
                [sys.executable, "-B", "scripts/generate_examples.py"],
                cwd=repository,
                capture_output=True,
                text=True,
                timeout=300,
            )

            self.assertEqual(
                0,
                completed.returncode,
                f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}",
            )
            after = file_bytes(repository)
            changed = sorted(
                relative
                for relative in before.keys() | after.keys()
                if before.get(relative) != after.get(relative)
            )
            self.assertEqual([], changed, "generated bytes changed")


if __name__ == "__main__":
    unittest.main()
